// Preview leads — one entry per HIGH priority prospect
// slug → URL: herbert-aisolutions.com/preview/[slug]

// Palette tokens. Each lead picks one via lead.palette.
// `mode` = 'light' (cream/off-white page bg, dark contained hero card)
//        or 'dark' (full dark page, hero text on bg directly)
export const PALETTES = {
  'navy-gold': {
    mode: 'dark',
    bg: '#0A1B2D',
    bgAlt: '#0F2436',
    ink: '#F5F0E5',
    inkSoft: '#E8E0CB',
    muted: 'rgba(245,240,229,0.6)',
    line: 'rgba(201,162,74,0.18)',
    card: 'rgba(245,240,229,0.04)',
    accent: '#D4B775',
    accentDeep: '#C9A24A',
    accentGlow: 'rgba(212,183,117,0.18)',
  },
  'cream-coral': {
    mode: 'light',
    bg: '#F5F0E5',
    bgAlt: '#EFE8D8',
    ink: '#0F0F0E',
    inkSoft: '#1F1F1E',
    muted: '#6B6660',
    line: '#E2DBCB',
    card: '#FFFFFF',
    accent: '#FF6B4A',
    accentDeep: '#E84F2E',
    accentGlow: 'rgba(255,107,74,0.18)',
  },
  'light-electric': {
    mode: 'light',
    bg: '#FAFAFA',
    bgAlt: '#F2F2F2',
    ink: '#0A0A0A',
    inkSoft: '#1A1A1A',
    muted: '#71717A',
    line: '#E4E4E7',
    card: '#FFFFFF',
    accent: '#3B82F6',
    accentDeep: '#2563EB',
    accentGlow: 'rgba(59,130,246,0.18)',
  },
  'cream-amber': {
    mode: 'light',
    bg: '#FAF6EC',
    bgAlt: '#F4EEDD',
    ink: '#1A1410',
    inkSoft: '#2A211B',
    muted: '#7A6A55',
    line: '#E5DCC4',
    card: '#FFFFFF',
    accent: '#E89456',
    accentDeep: '#D17638',
    accentGlow: 'rgba(232,148,86,0.20)',
  },
  'dark-mint': {
    mode: 'dark',
    bg: '#0F1F18',
    bgAlt: '#142922',
    ink: '#F0F5F2',
    inkSoft: '#D9E5DD',
    muted: 'rgba(240,245,242,0.6)',
    line: 'rgba(45,212,160,0.18)',
    card: 'rgba(240,245,242,0.04)',
    accent: '#3DDC97',
    accentDeep: '#2DD4A0',
    accentGlow: 'rgba(45,212,160,0.20)',
  },
  'slate-red': {
    mode: 'light',
    bg: '#F4F4F5',
    bgAlt: '#E9E9EB',
    ink: '#18181B',
    inkSoft: '#27272A',
    muted: '#71717A',
    line: '#E4E4E7',
    card: '#FFFFFF',
    accent: '#EF4444',
    accentDeep: '#DC2626',
    accentGlow: 'rgba(239,68,68,0.18)',
  },
}

const ELEC_SERVICES = [
  { title: 'Switchboard Upgrades', desc: 'Full panel upgrades and replacements for homes and businesses.' },
  { title: 'Safety Switch Installation', desc: 'Protect your family with compliant RCD safety switches.' },
  { title: 'Power Points & Lighting', desc: 'New points, LED upgrades, and custom lighting solutions.' },
  { title: 'EV Charger Installation', desc: 'Level 2 home EV charger install, certified and inspected.' },
]

const PLUMB_SERVICES = [
  { title: 'Emergency Plumbing', desc: 'Burst pipes, leaks, and blocked drains fixed fast — day or night.' },
  { title: 'Hot Water Systems', desc: 'Supply, install, and repair all major hot water brands.' },
  { title: 'Blocked Drains', desc: 'CCTV drain inspection and high-pressure jetting to clear blockages.' },
  { title: 'Leak Detection', desc: 'Non-invasive leak detection to find the problem before it gets worse.' },
]

export const leads = [
  {
    slug: 'adelaide-sparkys',
    biz: 'Adelaide Sparkys',
    owner: 'Simon',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: "Simon and the team — Adelaide's go-to electrician for fast, reliable work.",
    hero: "Fast, Reliable Electrical Work Across Adelaide",
    realReview: { name: 'Recent Google review', text: "Simon's follow-up was very efficient. Top quality work and great communication." },
    palette: 'cream-amber',
    vibe: 'Friendly local owner-operator. Simon is named in reviews — personal, responsive. Warm cream + amber suits the trustworthy local feel.',
  },
  {
    slug: 'adelaide-electric',
    biz: 'Adelaide Electric',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0423 057 185',
    services: ELEC_SERVICES,
    tagline: "Adelaide's trusted local electrician — licensed, insured, and always on time.",
    hero: "Adelaide's Trusted Local Electrician",
    palette: 'light-electric',
    vibe: 'Clean professional name, no personality hooks in the data — leans into modern minimal. Off-white + electric blue reads modern, trustworthy.',
  },
  {
    slug: 'amped-up-electrical',
    biz: 'Amped Up Electrical',
    owner: 'Marcus',
    trade: 'Electrician',
    suburb: 'Prospect',
    phone: '0468 008 822',
    services: ELEC_SERVICES,
    tagline: "Prospect's fast-response electrician. 30-min response. No surprises.",
    hero: "30-Minute Response. Every Time.",
    palette: 'cream-coral',
    vibe: 'Marcus advertises 30-min response on his Google ad — bold, energetic, response-focused positioning. Cream + coral matches the punchy confident operator.',
  },
  {
    slug: 'distinct-electrical',
    biz: 'Distinct Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0406 615 174',
    services: ELEC_SERVICES,
    tagline: "Quality electrical work across Adelaide — residential and commercial.",
    hero: "Quality Electrical Work, Done Right",
    palette: 'navy-gold',
    vibe: '"Distinct" name implies premium positioning. Has a website (rare among HIGH leads) so presents as more established. Navy + gold reads editorial/premium.',
  },
  {
    slug: 'electrician-services-adelaide',
    biz: 'Electrician Services Adelaide',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0487 269 444',
    services: ELEC_SERVICES,
    tagline: "Adelaide's reliable electrical service — available when you need us.",
    hero: "Reliable Electrical Services Across Adelaide",
    palette: 'slate-red',
    vibe: 'Generic descriptive business name, no character hooks. Slate + utility red reads honest/no-frills — fits a get-the-job-done operator.',
  },
  {
    slug: 'he-electrical',
    biz: 'H.E Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0404 785 157',
    services: ELEC_SERVICES,
    tagline: "Prompt, professional, and no-fuss electrical work across Adelaide.",
    hero: "Prompt. Professional. No Fuss.",
    realReview: { name: 'Recent Google review', text: "Prompt, no-fuss and incredibly knowledgeable. Highly recommend." },
    palette: 'navy-gold',
    vibe: 'Initials-based name, 24hr open, "prompt + knowledgeable" review — reads as skilled traditional tradesman. Navy + gold matches refined craftsperson positioning.',
  },
  {
    slug: 'just-trades',
    biz: 'Just Trades',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0400 825 329',
    services: ELEC_SERVICES,
    tagline: "Respect, reliability, and no shortcuts. That's Just Trades.",
    hero: "Respect. Reliability. No Shortcuts.",
    realReview: { name: 'Recent Google review', text: "Respect, reliability, taking pride. No shortcuts, no surprises." },
    palette: 'slate-red',
    vibe: 'Tagline is values-driven and uncompromising — no-shortcuts honest tradesman ethos. Slate + utility red matches the bold, hard-working operator.',
  },
  {
    slug: 'luma-electrical',
    biz: 'Luma Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0427 210 385',
    services: ELEC_SERVICES,
    tagline: "Reliable, professional, and fair-priced electrical work across Adelaide.",
    hero: "Reliable, Professional, Fair-Priced",
    realReview: { name: 'Recent Google review', text: "Reliable, professional and friendly, offering a fair price. Will use again." },
    palette: 'cream-amber',
    vibe: '"Luma" means light. Reviews emphasise friendly + fair-priced + reliable — warm balanced operator. Cream + amber matches the welcoming, light-and-warmth name.',
  },
  {
    slug: 'sole-elec',
    biz: 'SOLE ELEC',
    owner: 'Lenny',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0448 431 811',
    services: ELEC_SERVICES,
    tagline: "Adelaide's friendly local electrician — quality work, honest pricing.",
    hero: "Your Local Adelaide Electrician",
    palette: 'cream-coral',
    vibe: 'Lenny + Erin named in reviews — small personal team. "SOLE" hints at solo/owner-operator ethos. Cream + coral matches the personal, confident small-team feel.',
  },
  {
    slug: 'safe-ohms-electrical',
    biz: 'Safe Ohms Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0411 402 071',
    services: [
      ...ELEC_SERVICES.slice(0, 3),
      { title: 'Solar & Battery Systems', desc: 'Solar panel install, battery storage, and grid-connect systems.' },
    ],
    tagline: "Adelaide's reliable solar and electrical specialist.",
    hero: "Reliable Solar & Electrical Solutions",
    palette: 'dark-mint',
    vibe: 'Solar specialist — eco/renewable focus. Sponsored ad emphasises "Reliable Solar & Electrical". Deep forest + mint green directly signals eco-tech specialist.',
  },
  {
    slug: 'tcb-electrical',
    biz: 'TCB Electrical Services',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0429 348 000',
    services: ELEC_SERVICES,
    tagline: "Adelaide electricians you can count on — residential and commercial.",
    hero: "Adelaide Electricians You Can Count On",
    palette: 'light-electric',
    vibe: 'Initials-based name with no character hooks. Has a website (more established). Off-white + electric blue reads modern, professional, trustworthy.',
  },
  {
    slug: 'mcl-electrical',
    biz: 'MCL Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: "Professional electrical installations across the Adelaide metro area.",
    hero: "Professional Electrical Installations",
    palette: 'navy-gold',
    vibe: 'Initials-based name + Pty Ltd registered = more established/corporate. Has a working website. Navy + gold matches the refined professional installer.',
  },
  {
    slug: 'designa-plumbing',
    biz: 'Designa Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0408 497 554',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's plumber for quality residential and commercial work.",
    hero: "Quality Plumbing Across Adelaide",
    palette: 'dark-mint',
    vibe: '"Designa" hints at design-conscious branding — premium plumber positioning. Has a domain. Deep forest + mint reads distinctive and considered.',
  },
  {
    slug: 'sa-plumbing-solutions',
    biz: 'SA Plumbing Solutions',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0488 777 478',
    services: PLUMB_SERVICES,
    tagline: "Fast, reliable plumbing solutions across South Australia.",
    hero: "Fast, Reliable Plumbing Solutions",
    palette: 'light-electric',
    vibe: '"SA Plumbing Solutions" sounds corporate-clean, broad SA-wide reach. Off-white + electric blue suits the professional/corporate plumbing operator.',
  },
  {
    slug: 'ultimate-plumbing',
    biz: 'Ultimate Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Glenelg',
    phone: '0489 089 933',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's trusted plumber — emergency and scheduled work done right.",
    hero: "Adelaide's Trusted Plumber",
    palette: 'cream-coral',
    vibe: '"Ultimate" is a bold confident claim — operator who positions themselves as best-in-class. Cream + coral matches the bold confident voice.',
  },
  {
    slug: 'bj-plumbing',
    biz: 'BJ Plumbing Services',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0431 935 693',
    services: PLUMB_SERVICES,
    tagline: "Reliable plumbing services across Adelaide — call anytime.",
    hero: "Reliable Plumbing, Call Anytime",
    palette: 'slate-red',
    vibe: 'Initials-based name on Bigpond email — old-school utility plumber. Slate + utility red matches the no-frills, gets-the-job-done operator.',
  },
  {
    slug: 'wills-plumbing',
    biz: "Will's Plumbing Adelaide",
    owner: null,
    trade: 'Plumber',
    suburb: 'Malvern',
    phone: '0484 600 095',
    services: PLUMB_SERVICES,
    tagline: "Malvern and Adelaide's local plumber — fast, friendly, and fair.",
    hero: "Your Local Adelaide Plumber",
    palette: 'cream-amber',
    vibe: 'Named after the owner ("Will\'s"), Malvern-suburb-specific = warm local family plumber. Cream + amber matches the personal, neighbourhood-friendly feel.',
  },
]

export function getLead(slug) {
  return leads.find(l => l.slug === slug) ?? null
}
