// Preview leads — one entry per HIGH priority prospect
// slug → URL: herbert-aisolutions.com/preview/[slug]

const ELEC_SERVICES = [
  { title: 'Switchboard Upgrades', desc: 'Full panel upgrades and replacements for homes and businesses.' },
  { title: 'Safety Switch Installation', desc: 'Protect your family with compliant RCD safety switches.' },
  { title: 'Power Points & Lighting', desc: 'New points, LED upgrades, and custom lighting solutions.' },
  { title: 'EV Charger Installation', desc: 'Level 2 home EV charger install, certified and inspected.' },
]

const PLUMB_SERVICES = [
  { title: 'Emergency Plumbing', desc: 'Burst pipes, leaks, and blocked drains fixed fast — day or night.' },
  { title: 'Hot Water Systems', desc: 'Supply, install, and repair all major hot water brands.' },
  { title: 'Blocked Drains', desc: 'CCTV drain inspection and high-pressure jetting to clear blockages.' },
  { title: 'Leak Detection', desc: 'Non-invasive leak detection to find the problem before it gets worse.' },
]

export const leads = [
  {
    slug: 'adelaide-sparkys',
    biz: 'Adelaide Sparkys',
    owner: 'Simon',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: "Adelaide's go-to electrician for fast, reliable electrical work.",
    hero: "Fast, Reliable Electrical Work Across Adelaide",
    realReview: { name: 'Recent Google review', text: "Simon's follow-up was very efficient. Top quality work and great communication." },
  },
  {
    slug: 'adelaide-electric',
    biz: 'Adelaide Electric',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0423 057 185',
    services: ELEC_SERVICES,
    tagline: "Adelaide's trusted local electrician — licensed, insured, and always on time.",
    hero: "Adelaide's Trusted Local Electrician",
  },
  {
    slug: 'amped-up-electrical',
    biz: 'Amped Up Electrical',
    owner: 'Marcus',
    trade: 'Electrician',
    suburb: 'Prospect',
    phone: '0468 008 822',
    services: ELEC_SERVICES,
    tagline: "Prospect's fast-response electrician. 30-min response. No surprises.",
    hero: "30-Minute Response. Every Time.",
  },
  {
    slug: 'distinct-electrical',
    biz: 'Distinct Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0406 615 174',
    services: ELEC_SERVICES,
    tagline: "Quality electrical work across Adelaide — residential and commercial.",
    hero: "Quality Electrical Work, Done Right",
  },
  {
    slug: 'electrician-services-adelaide',
    biz: 'Electrician Services Adelaide',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0487 269 444',
    services: ELEC_SERVICES,
    tagline: "Adelaide's reliable electrical service — available when you need us.",
    hero: "Reliable Electrical Services Across Adelaide",
  },
  {
    slug: 'he-electrical',
    biz: 'H.E Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0404 785 157',
    services: ELEC_SERVICES,
    tagline: "Prompt, professional, and no-fuss electrical work across Adelaide.",
    hero: "Prompt. Professional. No Fuss.",
    realReview: { name: 'Recent Google review', text: "Prompt, no-fuss and incredibly knowledgeable. Highly recommend." },
  },
  {
    slug: 'just-trades',
    biz: 'Just Trades',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0400 825 329',
    services: ELEC_SERVICES,
    tagline: "Respect, reliability, and no shortcuts. That's Just Trades.",
    hero: "Respect. Reliability. No Shortcuts.",
    realReview: { name: 'Recent Google review', text: "Respect, reliability, taking pride. No shortcuts, no surprises." },
  },
  {
    slug: 'luma-electrical',
    biz: 'Luma Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0427 210 385',
    services: ELEC_SERVICES,
    tagline: "Reliable, professional, and fair-priced electrical work across Adelaide.",
    hero: "Reliable, Professional, Fair-Priced",
    realReview: { name: 'Recent Google review', text: "Reliable, professional and friendly, offering a fair price. Will use again." },
  },
  {
    slug: 'sole-elec',
    biz: 'SOLE ELEC',
    owner: 'Lenny',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0448 431 811',
    services: ELEC_SERVICES,
    tagline: "Adelaide's friendly local electrician — quality work, honest pricing.",
    hero: "Your Local Adelaide Electrician",
  },
  {
    slug: 'safe-ohms-electrical',
    biz: 'Safe Ohms Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0411 402 071',
    services: [
      ...ELEC_SERVICES.slice(0, 3),
      { title: 'Solar & Battery Systems', desc: 'Solar panel install, battery storage, and grid-connect systems.' },
    ],
    tagline: "Adelaide's reliable solar and electrical specialist.",
    hero: "Reliable Solar & Electrical Solutions",
  },
  {
    slug: 'tcb-electrical',
    biz: 'TCB Electrical Services',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0429 348 000',
    services: ELEC_SERVICES,
    tagline: "Adelaide electricians you can count on — residential and commercial.",
    hero: "Adelaide Electricians You Can Count On",
  },
  {
    slug: 'mcl-electrical',
    biz: 'MCL Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: "Professional electrical installations across the Adelaide metro area.",
    hero: "Professional Electrical Installations",
  },
  {
    slug: 'designa-plumbing',
    biz: 'Designa Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0408 497 554',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's plumber for quality residential and commercial work.",
    hero: "Quality Plumbing Across Adelaide",
  },
  {
    slug: 'sa-plumbing-solutions',
    biz: 'SA Plumbing Solutions',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0488 777 478',
    services: PLUMB_SERVICES,
    tagline: "Fast, reliable plumbing solutions across South Australia.",
    hero: "Fast, Reliable Plumbing Solutions",
  },
  {
    slug: 'ultimate-plumbing',
    biz: 'Ultimate Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Glenelg',
    phone: '0489 089 933',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's trusted plumber — emergency and scheduled work done right.",
    hero: "Adelaide's Trusted Plumber",
  },
  {
    slug: 'bj-plumbing',
    biz: 'BJ Plumbing Services',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0431 935 693',
    services: PLUMB_SERVICES,
    tagline: "Reliable plumbing services across Adelaide — call anytime.",
    hero: "Reliable Plumbing, Call Anytime",
  },
  {
    slug: 'wills-plumbing',
    biz: "Will's Plumbing Adelaide",
    owner: null,
    trade: 'Plumber',
    suburb: 'Malvern',
    phone: '0484 600 095',
    services: PLUMB_SERVICES,
    tagline: "Malvern and Adelaide's local plumber — fast, friendly, and fair.",
    hero: "Your Local Adelaide Plumber",
  },
]

export function getLead(slug) {
  return leads.find(l => l.slug === slug) ?? null
}
