// Preview leads — one entry per HIGH priority prospect
// slug → URL: herbert-aisolutions.com/preview/[slug]
//
// Each lead uses the `tradie-premium` preset from the web-design skill.
// Palette = trade-conventional colour scheme (navy + safety orange,
// charcoal + copper, deep teal + brass, etc.) — NOT the SaaS palettes
// we use elsewhere. See SKILL.md → tradie-premium for full system.

export const PALETTES = {
  'plumber-classic': {
    bg: '#F7F5F2',
    bgAlt: '#EFEBE5',
    ink: '#0E1B2C',
    inkSoft: '#1B2A3D',
    muted: '#5C6573',
    line: '#DCD7CD',
    card: '#FFFFFF',
    accent: '#F26B1F',
    accentDeep: '#D9591A',
    accentText: '#FFFFFF',     // text colour on accent backgrounds
    accentGlow: 'rgba(242,107,31,0.18)',
    label: 'Plumber',
  },
  'plumber-emergency': {
    bg: '#FFFFFF',
    bgAlt: '#F2F2F2',
    ink: '#0A0A0A',
    inkSoft: '#1A1A1A',
    muted: '#52525B',
    line: '#E4E4E7',
    card: '#FFFFFF',
    accent: '#D7263D',
    accentDeep: '#B81E32',
    accentText: '#FFFFFF',
    accentGlow: 'rgba(215,38,61,0.18)',
    label: 'Plumber · Emergency',
  },
  'plumber-premium': {
    bg: '#F7F5F2',
    bgAlt: '#ECE7DE',
    ink: '#0E4D52',
    inkSoft: '#0B3D40',
    muted: '#5C6573',
    line: '#D4CEC1',
    card: '#FFFFFF',
    accent: '#C8A24A',
    accentDeep: '#A88735',
    accentText: '#0E4D52',
    accentGlow: 'rgba(200,162,74,0.20)',
    label: 'Master Plumber',
  },
  'sparky-classic': {
    bg: '#F7F5F2',
    bgAlt: '#EFEBE5',
    ink: '#0F1A2E',
    inkSoft: '#1A2740',
    muted: '#5C6573',
    line: '#DCD7CD',
    card: '#FFFFFF',
    accent: '#F5C518',
    accentDeep: '#D6A912',
    accentText: '#0F1A2E',     // text on yellow stays dark for contrast
    accentGlow: 'rgba(245,197,24,0.22)',
    label: 'Licensed Electrician',
  },
  'sparky-premium': {
    bg: '#F7F5F2',
    bgAlt: '#ECE7DE',
    ink: '#1B1B1B',
    inkSoft: '#2A2A2A',
    muted: '#5C5C5C',
    line: '#D4CEC1',
    card: '#FFFFFF',
    accent: '#B5651D',
    accentDeep: '#9A5318',
    accentText: '#FFFFFF',
    accentGlow: 'rgba(181,101,29,0.20)',
    label: 'Master Electrician',
  },
  'sparky-eco': {
    bg: '#F7F5F2',
    bgAlt: '#E8EFE9',
    ink: '#0F2818',
    inkSoft: '#163525',
    muted: '#5A6B5F',
    line: '#D2DDD3',
    card: '#FFFFFF',
    accent: '#2DD477',
    accentDeep: '#1FB060',
    accentText: '#0F2818',
    accentGlow: 'rgba(45,212,119,0.20)',
    label: 'Solar & Electrical',
  },
}

// ─── Service catalogues ──────────────────────────────────────────────

const ELEC_SERVICES = [
  { title: 'Switchboard Upgrades', desc: 'Full panel upgrades and replacements for homes and businesses.' },
  { title: 'Safety Switch Installation', desc: 'Protect your family with compliant RCD safety switches.' },
  { title: 'Power Points & Lighting', desc: 'New points, LED upgrades, and custom lighting solutions.' },
  { title: 'EV Charger Installation', desc: 'Level 2 home EV charger install, certified and inspected.' },
]

const PLUMB_SERVICES = [
  { title: 'Emergency Plumbing', desc: 'Burst pipes, leaks, and blocked drains fixed fast — day or night.' },
  { title: 'Hot Water Systems', desc: 'Supply, install, and repair all major hot water brands.' },
  { title: 'Blocked Drains', desc: 'CCTV drain inspection and high-pressure jetting to clear blockages.' },
  { title: 'Leak Detection', desc: 'Non-invasive leak detection to find the problem before it gets worse.' },
]

// ─── Adelaide suburb pool ────────────────────────────────────────────

const ADELAIDE_SUBURBS = [
  'Norwood', 'Burnside', 'Henley Beach', 'Glenelg', 'Prospect',
  'Walkerville', 'Magill', 'Unley', 'Mitcham', 'Marion',
  'Kensington', 'St Peters', 'Hyde Park', 'Brighton', 'Semaphore',
  'Adelaide CBD', 'Stepney', 'Payneham', 'Toorak Gardens', 'Goodwood',
]

// ─── Leads ───────────────────────────────────────────────────────────

export const leads = [
  {
    slug: 'adelaide-sparkys',
    biz: 'Adelaide Sparkys',
    owner: 'Simon',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: "Adelaide's go-to electrician for fast, reliable electrical work.",
    hero: 'Fast, reliable electrical work across Adelaide.',
    eyebrow: 'Adelaide-wide · Mobile electrician',
    yearsLabel: 'Adelaide local',
    realReview: { name: 'Simon\'s recent Google review', text: "Simon's follow-up was very efficient. Top quality work and great communication." },
    palette: 'sparky-classic',
    vibe: 'Friendly local owner-operator. Simon is named in reviews — personal, responsive.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'adelaide-electric',
    biz: 'Adelaide Electric',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0423 057 185',
    services: ELEC_SERVICES,
    tagline: "Adelaide's trusted local electrician — licensed, insured, and always on time.",
    hero: "Adelaide's trusted local electrician.",
    eyebrow: 'Adelaide · Domestic & commercial',
    yearsLabel: 'Adelaide local',
    palette: 'sparky-classic',
    vibe: 'Clean professional name, no personality hooks. Default sparky palette.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'amped-up-electrical',
    biz: 'Amped Up Electrical',
    owner: 'Marcus',
    trade: 'Electrician',
    suburb: 'Prospect',
    phone: '0468 008 822',
    services: ELEC_SERVICES,
    tagline: "Prospect's fast-response electrician. 30-min response. No surprises.",
    hero: '30-minute response. Every time.',
    eyebrow: 'Prospect · Fast-response sparky',
    yearsLabel: '30-min response · Adelaide',
    palette: 'sparky-classic',
    vibe: 'Marcus advertises 30-min response — bold, energetic, response-focused. Yellow accent matches the punchy positioning.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'distinct-electrical',
    biz: 'Distinct Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0406 615 174',
    services: ELEC_SERVICES,
    tagline: 'Quality electrical work across Adelaide — residential and commercial.',
    hero: 'Quality electrical work, done right.',
    eyebrow: 'Adelaide · Residential & commercial',
    yearsLabel: 'Adelaide premium electrician',
    palette: 'sparky-premium',
    vibe: '"Distinct" implies premium. Has a website. Charcoal + copper for refined operator.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'electrician-services-adelaide',
    biz: 'Electrician Services Adelaide',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0487 269 444',
    services: ELEC_SERVICES,
    tagline: "Adelaide's reliable electrical service — available when you need us.",
    hero: 'Reliable electrical services, Adelaide-wide.',
    eyebrow: 'Adelaide · 7-day service',
    yearsLabel: 'Adelaide local · Available 7 days',
    palette: 'sparky-classic',
    vibe: 'Generic descriptive name. Default sparky palette for utility/get-it-done.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'he-electrical',
    biz: 'H.E Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0404 785 157',
    services: ELEC_SERVICES,
    tagline: 'Prompt, professional, and no-fuss electrical work across Adelaide.',
    hero: 'Prompt. Professional. No fuss.',
    eyebrow: 'Adelaide · 24-hour electrician',
    yearsLabel: '24/7 callouts · Adelaide',
    realReview: { name: 'Recent Google review', text: 'Prompt, no-fuss and incredibly knowledgeable. Highly recommend.' },
    palette: 'sparky-premium',
    vibe: 'Initials, 24hr open, "prompt + knowledgeable" reviews — skilled traditional tradesman. Charcoal + copper.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'just-trades',
    biz: 'Just Trades',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0400 825 329',
    services: ELEC_SERVICES,
    tagline: "Respect, reliability, and no shortcuts. That's Just Trades.",
    hero: 'Respect. Reliability. No shortcuts.',
    eyebrow: 'Adelaide · Residential electrical',
    yearsLabel: 'Family-owned · Adelaide',
    realReview: { name: 'Recent Google review', text: 'Respect, reliability, taking pride. No shortcuts, no surprises.' },
    palette: 'sparky-classic',
    vibe: 'Values-driven, no-nonsense. Bold yellow matches the unapologetic ethos.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'luma-electrical',
    biz: 'Luma Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0427 210 385',
    services: ELEC_SERVICES,
    tagline: 'Reliable, professional, and fair-priced electrical work across Adelaide.',
    hero: 'Reliable, professional, fair-priced.',
    eyebrow: 'Adelaide · Lighting & power specialists',
    yearsLabel: 'Adelaide local',
    realReview: { name: 'Recent Google review', text: 'Reliable, professional and friendly, offering a fair price. Will use again.' },
    palette: 'sparky-premium',
    vibe: '"Luma" = light. Reviews emphasise warmth + fair price. Copper accent matches.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'sole-elec',
    biz: 'SOLE ELEC',
    owner: 'Lenny',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0448 431 811',
    services: ELEC_SERVICES,
    tagline: "Adelaide's friendly local electrician — quality work, honest pricing.",
    hero: 'Your local Adelaide electrician.',
    eyebrow: 'Adelaide · Owner-operator',
    yearsLabel: 'Lenny + Erin · Adelaide',
    palette: 'sparky-classic',
    vibe: 'Lenny + Erin in reviews — small personal team. Default sparky colour for personal owner-operator.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'safe-ohms-electrical',
    biz: 'Safe Ohms Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0411 402 071',
    services: [
      ...ELEC_SERVICES.slice(0, 3),
      { title: 'Solar & Battery Systems', desc: 'Solar panel install, battery storage, and grid-connect systems.' },
    ],
    tagline: "Adelaide's reliable solar and electrical specialist.",
    hero: 'Reliable solar & electrical solutions.',
    eyebrow: 'Adelaide · Solar specialist',
    yearsLabel: 'Solar specialist · Adelaide',
    palette: 'sparky-eco',
    vibe: 'Solar specialist — eco/renewable focus. Deep forest + emerald signals it directly.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'tcb-electrical',
    biz: 'TCB Electrical Services',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0429 348 000',
    services: ELEC_SERVICES,
    tagline: 'Adelaide electricians you can count on — residential and commercial.',
    hero: 'Adelaide electricians you can count on.',
    eyebrow: 'Adelaide · Residential & commercial',
    yearsLabel: 'Adelaide local',
    palette: 'sparky-classic',
    vibe: 'Initials. Has a website. Default sparky colour for established operator.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'mcl-electrical',
    biz: 'MCL Electrical',
    owner: null,
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0432 278 322',
    services: ELEC_SERVICES,
    tagline: 'Professional electrical installations across the Adelaide metro area.',
    hero: 'Professional electrical installations.',
    eyebrow: 'Adelaide metro · Pty Ltd',
    yearsLabel: 'Adelaide metro · Pty Ltd',
    palette: 'sparky-premium',
    vibe: 'Pty Ltd registered, more established. Charcoal + copper for refined corporate.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'designa-plumbing',
    biz: 'Designa Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0408 497 554',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's plumber for quality residential and commercial work.",
    hero: 'Quality plumbing across Adelaide.',
    eyebrow: 'Adelaide · Residential & commercial',
    yearsLabel: 'Adelaide premium plumber',
    palette: 'plumber-premium',
    vibe: '"Designa" hints at design-conscious branding — premium positioning. Deep teal + brass.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'sa-plumbing-solutions',
    biz: 'SA Plumbing Solutions',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0488 777 478',
    services: PLUMB_SERVICES,
    tagline: 'Fast, reliable plumbing solutions across South Australia.',
    hero: 'Fast, reliable plumbing solutions.',
    eyebrow: 'South Australia · 7-day service',
    yearsLabel: 'SA-wide · 7 days',
    palette: 'plumber-classic',
    vibe: 'Corporate-clean, broad SA-wide reach. Navy + safety orange = default plumber.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'ultimate-plumbing',
    biz: 'Ultimate Plumbing',
    owner: null,
    trade: 'Plumber',
    suburb: 'Glenelg',
    phone: '0489 089 933',
    services: PLUMB_SERVICES,
    tagline: "Adelaide's trusted plumber — emergency and scheduled work done right.",
    hero: "Adelaide's trusted plumber.",
    eyebrow: 'Glenelg · 24-hour emergency',
    yearsLabel: '24/7 emergency · Glenelg',
    palette: 'plumber-emergency',
    vibe: '"Ultimate" is bold — and emergency positioning works. Black + red for emergency confidence.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'bj-plumbing',
    biz: 'BJ Plumbing Services',
    owner: null,
    trade: 'Plumber',
    suburb: 'Adelaide',
    phone: '0431 935 693',
    services: PLUMB_SERVICES,
    tagline: 'Reliable plumbing services across Adelaide — call anytime.',
    hero: 'Reliable plumbing, call anytime.',
    eyebrow: 'Adelaide · 7-day service',
    yearsLabel: 'Adelaide local · Family-owned',
    palette: 'plumber-classic',
    vibe: 'Initials, Bigpond email, old-school utility plumber. Navy + safety orange.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'wills-plumbing',
    biz: "Will's Plumbing Adelaide",
    owner: null,
    trade: 'Plumber',
    suburb: 'Malvern',
    phone: '0484 600 095',
    services: PLUMB_SERVICES,
    tagline: "Malvern and Adelaide's local plumber — fast, friendly, and fair.",
    hero: 'Your local Malvern plumber.',
    eyebrow: 'Malvern · Family-owned',
    yearsLabel: 'Family-owned · Malvern',
    palette: 'plumber-premium',
    vibe: 'Named after owner ("Will\'s"), suburb-specific. Premium teal + brass for warm local trade.',
    suburbs: ADELAIDE_SUBURBS,
  },
  {
    slug: 'wired-up-electrical',
    biz: 'Wired Up Electrical Co',
    owner: 'Hugh',
    trade: 'Electrician',
    suburb: 'Adelaide',
    phone: '0449 091 886',
    services: ELEC_SERVICES,
    tagline: "Adelaide's 24-hour electrician — Hugh's there when the power goes out.",
    hero: "Adelaide's 24-hour electrician.",
    eyebrow: 'Adelaide · 24-hr emergency',
    yearsLabel: '24/7 callouts · Adelaide',
    realReview: { name: 'Recent Google review', text: "Hugh came out quickly, late at night when we had no power. Couldn't recommend more." },
    palette: 'sparky-classic',
    vibe: 'Hugh named in reviews, emergency/after-hours is his niche. Bold navy + yellow for 24hr confidence.',
    suburbs: ADELAIDE_SUBURBS,
  },
]

export function getLead(slug) {
  return leads.find(l => l.slug === slug) ?? null
}
